/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// MaaSConfigApplyConfiguration represents a declarative configuration of the MaaSConfig type for use
// with apply.
type MaaSConfigApplyConfiguration struct {
	Endpoint  *string `json:"endpoint,omitempty"`
	APIKey    *string `json:"apiKey,omitempty"`
	Zone      *string `json:"zone,omitempty"`
	DNSDomain *string `json:"dnsDomain,omitempty"`
}

// MaaSConfigApplyConfiguration constructs a declarative configuration of the MaaSConfig type for use with
// apply.
func MaaSConfig() *MaaSConfigApplyConfiguration {
	return &MaaSConfigApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *MaaSConfigApplyConfiguration) WithEndpoint(value string) *MaaSConfigApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithAPIKey sets the APIKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIKey field is set to the value of the last call.
func (b *MaaSConfigApplyConfiguration) WithAPIKey(value string) *MaaSConfigApplyConfiguration {
	b.APIKey = &value
	return b
}

// WithZone sets the Zone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Zone field is set to the value of the last call.
func (b *MaaSConfigApplyConfiguration) WithZone(value string) *MaaSConfigApplyConfiguration {
	b.Zone = &value
	return b
}

// WithDNSDomain sets the DNSDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSDomain field is set to the value of the last call.
func (b *MaaSConfigApplyConfiguration) WithDNSDomain(value string) *MaaSConfigApplyConfiguration {
	b.DNSDomain = &value
	return b
}
